nav:
  - Home: index.md
  - Core Topics:
      - Hilbert Rendering Zone: hilbert-rendering-zone.md
      - Informational Substrate: informational-substrate.md
      - Quasi-crystalline Structure: quasicrystalline-structure.md
      - Bose–Einstein Condensate: bose-einstein-condensate.md
      - Informational Collapse Hierarchy: informational-collapse-hierarchy.md
      - Entanglement: entanglement.md
      - Wave Function Collapse: wave-function-collapse.md
      - Reductionist Point of View: reductionist-point-of-view.md
      - Nested HRZ Model: nested-hrz-model.md
      - Codex Interaction Models: codex-interaction-models.md
